import { integer, pgTable, timestamp, varchar } from 'drizzle-orm/pg-core';
import {
    createInsertSchema,
    createSelectSchema,
} from 'drizzle-zod';
import { relations } from 'drizzle-orm';
import type { z } from 'zod';

import { users } from './user.schema.js';

// ------------------------------------------------------------------
// 1. DRiZZLE SCHEMA (Source of Truth)
// ------------------------------------------------------------------
// This is your main table definition.
// The Zod schemas will be automatically generated from this.
// ------------------------------------------------------------------

export const farmersTable = pgTable('farmers', {
    id: integer("id").primaryKey().generatedAlwaysAsIdentity({ startWith: 1 }),
    farmer_name: varchar('farmer_name', { length: 200 }).notNull(),
    phone_number: varchar('phone_number', { length: 50 }).unique().notNull(),

    sector: varchar('sector', { length: 100 }).notNull(),
    cell: varchar('cell', { length: 100 }),
    village: varchar('village', { length: 100 }),

    collection_center_id: integer('collection_center_id').notNull().references(() => users.id, { onDelete: 'cascade' }),

    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
});


export const farmersRelations = relations(farmersTable, ({ one }) => ({
    collectionCenter: one(users, {
        fields: [farmersTable.collection_center_id],
        references: [users.id],
    }),
}));

// ------------------------------------------------------------------
// 2. ZOD SCHEMAS (Derived from Drizzle Schema)
// ------------------------------------------------------------------
// These schemas are used to validate data at different points
// in your application (e.g., API inputs, database outputs).
// ------------------------------------------------------------------

/**
 * ## insertFarmerSchema
 * Use this to validate data when **creating** a new farmer via API request body.
 * - `id`, `createdAt`, `updatedAt` are excluded (auto-generated by DB).
 * - `collection_center_id` is excluded (should be added in the controller based on logged-in user).
 * - Refinements add specific validation rules (e.g., minimum length).
 */
export const insertFarmerSchema = createInsertSchema(farmersTable, {
    farmer_name: (schema) =>
        schema
            .min(2, { message: 'Farmer name must be at least 2 characters long' })
            .max(200, { message: 'Farmer name cannot exceed 200 characters' }),

    phone_number: (schema) =>
        schema
            .regex(/^(\+?25)?(07[2389])[0-9]{7}$/, { message: "Invalid Rwandan phone number format" }),

    sector: (schema) =>
        schema
            .min(2, { message: 'Sector must be at least 2 characters long' })
            .max(100, { message: 'Sector cannot exceed 100 characters' }),

    cell: (schema) =>
        schema
            .min(2, { message: 'Sector must be at least 2 characters long' })
            .max(100, { message: 'Cell cannot exceed 100 characters' }),

    village: (schema) =>
        schema
            .min(2, { message: 'Sector must be at least 2 characters long' })
            .max(100, { message: 'Village cannot exceed 100 characters' })
}).omit({
    id: true,
    createdAt: true,
    updatedAt: true,
    collection_center_id: true,
});


export const selectFarmerSchema = createSelectSchema(farmersTable).omit({
    updatedAt: true,
});


// export const updateUserSchema = createUpdateSchema(users, {
//     email: (schema) =>
//         schema.email({ message: 'Invalid email address' }).optional(),
//     password: (schema) =>
//         schema.min(8, { message: 'Password must be at least 8 characters' }).optional(),
// });


// ------------------------------------------------------------------
// 3. TYPESCRIPT TYPES (Derived from Zod Schemas)
// ------------------------------------------------------------------

/**
 * Represents a farmer as it is returned from the database (updatedAt omitted).
 */
export type Farmer = z.infer<typeof selectFarmerSchema>;

/**
 * Represents the data needed to create a new user.
 */
export type NewFarmer = z.infer<typeof insertFarmerSchema>;


// export type UpdateUser = z.infer<typeof updateUserSchema>;



