import { decimal, integer, pgTable, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { relations } from "drizzle-orm";
import { z } from "zod";

import { users } from "./user.schema.js";
import { farmersTable } from "./farmer.schema.js";

// ------------------------------------------------------------------
// 1. DRiZZLE SCHEMA (Source of Truth)
// ------------------------------------------------------------------
// This is your main table definition.
// The Zod schemas will be automatically generated from this.
// ------------------------------------------------------------------

export const milkRecordsTable = pgTable("milk_records", {
  id: integer("id").primaryKey().generatedAlwaysAsIdentity({ startWith: 1 }),

  liters: decimal("liters", { precision: 10, scale: 2 }).notNull(),
  price_per_liter: decimal("price_per_liter", {
    precision: 10,
    scale: 3,
  }).notNull(),

  farmer_id: integer("farmer_id")
    .notNull()
    .references(() => farmersTable.id, { onDelete: "restrict" }),

  recorded_by_collection_id: integer("recorded_by_collection_id")
    .notNull()
    .references(() => users.id, { onDelete: "restrict" }),

  recordedAt: timestamp("recorded_at", { mode: "date", withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const milkRecordsRelations = relations(milkRecordsTable, ({ one }) => ({
  farmer: one(farmersTable, {
    fields: [milkRecordsTable.farmer_id],
    references: [farmersTable.id],
  }),
  recordedBy: one(users, {
    fields: [milkRecordsTable.recorded_by_collection_id],
    references: [users.id],
  }),
}));

// ------------------------------------------------------------------
// 2. ZOD SCHEMAS (Derived from Drizzle Schema)
// ------------------------------------------------------------------
// These schemas are used to validate data at different points
// in your application (e.g., API inputs, database outputs).
// ------------------------------------------------------------------

/**
 * ## insertMilkRecordSchema
 * Use this to validate data when **creating** a new milk record via API request body.
 * - `id`, `recordedAt`, `updatedAt` are excluded (auto-generated by DB).
 * - `recorded_by_collection_id` is excluded (should be added in the controller based on logged-in user).
 * - Refinements add specific validation rules.
 */
export const insertMilkRecordSchema = createInsertSchema(milkRecordsTable, {
  /**
   * 'liters' is a decimal, which drizzle-zod maps to a string.
   * We override it to coerce the string (from JSON) into a number
   * and apply numeric validation.
   */

  liters: z.coerce
    .number({
      error: "Liters must be a valid number.",
    })
    .positive({ message: "Liters must be greater than 0." })
    .multipleOf(0.01, {
      message: "Liters cannot have more than 2 decimal places.",
    })
    .max(99999999.99, { message: "Liters value is too large." }),
  price_per_liter: z.coerce
    .number({
      error: "Price per litre must be a valid number.",
    })
    .positive({ message: "Price per litre must be greater than 0." })
    .multipleOf(0.01, {
      message: "Liters cannot have more than 3 decimal places.",
    })
    .max(99999999.99, { message: "Liters value is too large." }),

  farmer_id: z.coerce
    .number({
      error: "Farmer ID must be a number.",
    })
    .int({ message: "Farmer ID must be an integer." })
    .positive({ message: "A valid Farmer ID is required." }),
}).omit({
  recorded_by_collection_id: true,
});

/**
 * ## selectMilkRecordSchema
 * Use this to validate data when **selecting** or returning a milk record.
 */
export const selectMilkRecordSchema = createSelectSchema(milkRecordsTable);

// ------------------------------------------------------------------
// 3. TYPESCRIPT TYPES (Derived from Zod Schemas)
// ------------------------------------------------------------------

/**
 * Represents a milk record as it is returned from the database (updatedAt omitted).
 */
export type MilkRecord = z.infer<typeof selectMilkRecordSchema>;

/**
 * Represents the data needed to create a new milk record.
 */
export type NewMilkRecord = z.infer<typeof insertMilkRecordSchema>;
